name: Publish to NPM

# Publish is started on release creation in the UI
on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds
      - name: Install dependencies 🔧
        run: npm ci
      - name: Build project 🏗️
        run: npm run build --if-present
      - name: Publish package on NPM 📦
        run: npm publish --dry-run

